openapi: 3.0.3
info:
  title: Master API Contract
  version: 1.0.0
paths: { }
components:
  schemas:
    # doku(s)
    DokuStatusRequest:
      $ref: '../api-doku.yaml#/components/schemas/DokuStatusRequest'
    DokuStatusResponse:
      $ref: '../api-doku.yaml#/components/schemas/DokuStatusResponse'
    # api(s)
    PaymentRequest:
      $ref: '../api-payment.yaml#/components/schemas/PaymentRequest'
    PaymentResponse:
      $ref: '../api-payment.yaml#/components/schemas/PaymentResponse'
    StatusRequest:
      $ref: '../api-payment.yaml#/components/schemas/StatusRequest'
    StatusResponse:
      $ref: '../api-payment.yaml#/components/schemas/StatusResponse'
    TokenRequest:
      $ref: '../api-token.yaml#/components/schemas/TokenRequest'
    TokenResponse:
      $ref: '../api-token.yaml#/components/schemas/TokenResponse'
    VaRequest:
      $ref: '../api-va.yaml#/components/schemas/VaRequest'
    VaResponse:
      $ref: '../api-va.yaml#/components/schemas/VaResponse'
    # data(s)
    AdditionalData:
      $ref: '../data-additional.yaml#/components/schemas/AdditionalData'
    AdditionalSettingData:
      $ref: '../data-additional-setting.yaml#/components/schemas/AdditionalSettingData'
    AmountData:
      $ref: '../data-amount.yaml#/components/schemas/AmountData'
    ErrorData:
      $ref: '../data-error.yaml#/components/schemas/ErrorData'
    # type(s)
    Channel:
      $ref: '../type-channel.yaml#/components/schemas/Channel'
    GrantType:
      $ref: '../type-grant.yaml#/components/schemas/GrantType'
    PaymentType:
      $ref: '../type-payment.yaml#/components/schemas/PaymentType'
    StatusType:
      $ref: '../type-status.yaml#/components/schemas/StatusType'
    TokenType:
      $ref: '../type-token.yaml#/components/schemas/TokenType'
    TokenScheme:
      $ref: '../type-token-scheme.yaml#/components/schemas/TokenScheme'
    TransactionType:
      $ref: '../type-transaction.yaml#/components/schemas/TransactionType'