openapi: 3.0.3
info:
  title: Token API
  version: 1.0.0
paths: { }
components:
  schemas:
    TokenRequest:
      type: object
      properties:
        clientId:
          type: string
          example: BRS-001-000...
          x-field-extra-annotation: |
            @jakarta.validation.constraints.NotNull(message = "paymentId must not be null")
            @jakarta.validation.constraints.NotBlank(message = "paymentId must not be empty")
        tokenType:
          $ref: './type-token.yaml#/components/schemas/TokenType'
        grantType:
          $ref: './type-grant.yaml#/components/schemas/GrantType'
    TokenResponse:
      type: object
      properties:
        tokenScheme:
          type: string
          example: Bearer
        accessToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR...
        accessTokenExpiryTime:
          type: string
          format: instant
          example: "2025-08-20T12:00:00Z"
        refreshToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR...
        refreshTokenExpiryTime:
          type: string
          format: instant
          example: "2025-08-27T12:00:00Z"
        expiresIn:
          type: integer
          example: 3600
        additionalInfo:
          type: string
          example: Some metadata here
        error:
          $ref: './data-error.yaml#/components/schemas/ErrorData'