openapi: 3.0.3
info:
  title: Amount Data Schema
  version: 1.0.0
paths: { }
components:
  schemas:
    AmountData:
      type: object
      properties:
        value:
          type: string
          format: big_decimal
          example: "100000.00"
          x-field-extra-annotation: |
            @jakarta.validation.constraints.NotNull(message = "amount.value must not be null")
            @jakarta.validation.constraints.DecimalMin(value = "0.0", inclusive = false, message = "amount.value must be greater than zero")
            @jakarta.validation.constraints.Digits(integer = 17, fraction = 2, message = "amount.value must be a number with max 17 digits and 2 decimal places")
        currency:
          type: string
          example: "IDR"
          x-field-extra-annotation: |
            @jakarta.validation.constraints.NotNull(message = "amount.currency must not be null")
            @jakarta.validation.constraints.NotBlank(message = "amount.currency must not be empty")
            @jakarta.validation.constraints.Size(min = 3, max = 3, message = "amount.currency must be exactly 3 characters")