openapi: 3.0.3
info:
  title: Header Data Schema
  version: 1.0.0
paths: { }
components:
  schemas:
    HeaderData:
      type: object
      properties:
        clientId:
          type: string
          example: my-client
        requestId:
          type: string
          example: 0000000001
        channelId:
          type: string
          example: H2H
        token:
          type: string
          example: eyJhbGciOi...
        tokenScheme:
          type: string
          example: Bearer
        signature:
          type: string
          example: e8757c8de...
        timestamp:
          type: string
          format: instant
          example: "2025-08-20T12:00:00Z"
      required: [ clientId, token, tokenScheme ]