openapi: 3.0.3
info:
  title: Additional Setting Data Schema
  version: 1.0.0
paths: { }
components:
  schemas:
    AdditionalSettingData:
      type: object
      properties:
        reusableStatus:
          type: boolean
          example: true
        minAmount:
          type: string
          format: big_decimal
          example: "1000.00"
          x-field-extra-annotation: |
            @jakarta.validation.constraints.DecimalMin(value = "0.0", inclusive = false, message = "minAmount must be greater than zero")
            @jakarta.validation.constraints.Digits(integer = 17, fraction = 2, message = "minAmount must be a number with max 17 digits and 2 decimal places")
        maxAmount:
          type: string
          format: big_decimal
          example: "5000000.00"
          x-field-extra-annotation: |
            @jakarta.validation.constraints.DecimalMin(value = "0.0", inclusive = false, message = "maxAmount must be greater than zero")
            @jakarta.validation.constraints.Digits(integer = 17, fraction = 2, message = "maxAmount must be a number with max 17 digits and 2 decimal places")