openapi: 3.0.3
info:
  title: Error Data Schema
  version: 1.0.0
paths: { }
components:
  schemas:
    ErrorData:
      type: object
      description: Common error structure
      properties:
        status:
          type: integer
          description: Numeric HTTP status code
          example: 400
        responseCode:
          type: string
          description: Application error code
          example: "40327 + case_code"
        responseMessage:
          type: string
          description: Optional application error message
          example: Invalid request
      required: [ status, responseCode ]