openapi: 3.0.3
info:
  title: Error Data Schema
  version: 1.0.0
paths: { }
components:
  schemas:
    ErrorData:
      type: object
      properties:
        status:
          type: integer
          example: 400
        code:
          type: string
          example: "40327 + case_code"
          x-field-extra-annotation: |
            @com.fasterxml.jackson.annotation.JsonProperty("responseCode")
        message:
          type: string
          example: Unknown server error
          x-field-extra-annotation: |
            @com.fasterxml.jackson.annotation.JsonProperty("responseMessage")