openapi: 3.0.3
info:
  title: Transaction Type Schema
  version: 1.0.0
paths: { }
components:
  schemas:
    TransactionType:
      type: string
      enum:
        - C
        - O
      x-enum-descriptions:
        - "Closed Amount"
        - "Open Amount"
      example: C
      x-field-extra-annotation: |
        @com.fasterxml.jackson.annotation.JsonProperty("virtualAccountTrxType")