openapi: 3.0.3
info:
  title: Transaction Type Schema
  version: 1.0.0
paths: { }
components:
  schemas:
    TransactionType:
      type: string
      enum: [ C, O ]
      example: C
      description: |
        C = Closed Amount
        O = Open Amount
      x-field-extra-annotation: |
        @jakarta.validation.constraints.NotNull(message = "transactionType must not be null")