openapi: 3.0.3
info:
  title: Grant Type Schema
  version: 1.0.0
paths: { }
components:
  schemas:
    GrantType:
      type: string
      enum: [ client_credentials, authorization_code ]
      example: client_credentials
      x-field-extra-annotation: |
        @jakarta.validation.constraints.NotNull(message = "grantType must not be null")