openapi: 3.0.3
info:
  title: Token Type Schema
  version: 1.0.0
paths: { }
components:
  schemas:
    TokenType:
      type: string
      enum:
        - b2b
        - b2b2c
      x-enum-descriptions:
        - "B2B Token"
        - "B2B2C Token"
      example: b2b
      x-field-extra-annotation: |
        @jakarta.validation.constraints.NotNull(message = "tokenType must not be null")