openapi: 3.0.3
info:
  title: Status Type Schema
  version: 1.0.0
paths: { }
components:
  schemas:
    StatusType:
      type: string
      enum:
        - pending
        - success
      x-enum-descriptions:
        - "Pending Payment"
        - "Success Payment"
      example: pending
      x-field-extra-annotation: |
        @jakarta.validation.constraints.NotNull(message = "statusType must not be null")