name: Publish Shared Library Package as Maven Dependency to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup java 21 temurin
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin

      - name: Build and publish package to GitHub Packages
        run: mvn clean deploy -DskipTests -s .github/settings.xml